### ISSUE TITLE
Hackintosh

### ISSUE THREAD

**Issue by vmwsree** [jgamblin/MacOS-Maid#3]
I just run this on hackintosh,
the system seems not responding even after restart the launcher hasnt shown its a black screen and a cursor, 
I seem like in a lot of trouble!

**Comment by mirkokg** [comment]
Me too. Probably some update it installed. Were you able to fix it?

**Comment by diwayou** [comment]
i see the script contains below
```
printf "Securely erasing free space (This will take a while). \n"
diskutil secureErase freespace 0 "$( df -h / | tail -n 1 | awk '{print $1}')" > /dev/null 2>&1
```

this will erase data, maybe this is the reason,
so do not use this script

**Comment by jgamblin** [comment]
That command only cleans free space, as laid out in this article. 
https://osxdaily.com/2016/04/28/erase-free-space-mac-command-line/
